# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NY Javascript
email: gil@nyjavascript.com
description: > # this means to ignore newlines until "baseurl:"
  We host regular workshops and tech talks on a variety of different JavaScript topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nyjavascript.github.io" # the base hostname & protocol for your site
meetup_url: "http://www.meetup.com/NY-JavaScript/"
twitter_username: nyjavascript
github_username:  nyjavascript

# Build settings
markdown: kramdown
